# spring:
#     datasource:
#         url: jdbc:mysql://localhost:3306/abet?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#         username: root
#         password: password
#         driver-class-name: com.mysql.cj.jdbc.Driver
#     jpa:
#         hibernate:
#         ddl-auto: none
#         show-sql: true
#         properties:
#         hibernate:
#             dialect: org.hibernate.dialect.MySQL8Dialect
#             format_sql: true
#     thymeleaf:
#         cache: false
#     servlet:
#         multipart:
#         max-file-size: 10MB
#         max-request-size: 10MB

# server:
#     error:
#         include-message: always
#         include-binding-errors: always
#     port: 8080

#     logging:
#     level:
#         org.springframework.web: INFO
#         com.university.syllabus: DEBUG
#         org.hibernate.SQL: DEBUG
#         org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#  # Custom application properties
# app:
#     name: "University Syllabus Management System"
#     version: "1.0.0"
#     admin-email: "admin@university.edu"
#     default-language: "en"
#     academic-years:
#         current: "2024-2025"
#         previous: "2023-2024"
#     export:
#         path: "/tmp/exports"
#         pdf-enabled: true